"""questions table

Revision ID: 1acab184958c
Revises: d54236ebae70
Create Date: 2020-05-03 14:10:17.631098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1acab184958c'
down_revision = 'd54236ebae70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('difficulty', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'difficulty')
    # ### end Alembic commands ###
